# Change these first
owner: springbeats # Your GitHub username
repo: springbeats-uptime # Your Github repository name

# Add your sites here
sites:
  - name: Springbeats Home
    url: https://springbeats.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.springbeats.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://avatars0.githubusercontent.com/u/74774613?s=200&v=4
  name: Springbeats
  introTitle: "**Springbeats** develops music software."
  introMessage: Such as Velpro, sbvmidi virtual midi cable, etc.
  navbar:
    - title: Status
      href: /
    - title: Springbeats Home
      href: https://springbeats.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
